Fix errors and typos in opsdroid.po
opsdroid/opsdroid pull request #1647
Opened 2020-10-02 07:42 UTC by virejdasani

# Description

There are typos and errors in the opsdroid/locale/hi/LC_MESSAGES/opsdroid.po
For example, the quotations are applied improperly. This causes some of the text to leak out of the string.

I have fixed all of these issues in my pull request by going line by line and fixing typos and quotation errors

Fixes #<1646>

## Status
**READY**

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

# Checklist:

- [ x] I have performed a self-review of my own code

2020-10-02 07:45 UTC, virejdasani commented
I have also added more translations that were previously commented out

2020-10-02 14:41 UTC, FabioRosado requested changes

2020-10-02 14:41 UTC, FabioRosado commented on opsdroid/locale/hi/LC_MESSAGES/opsdroid.po
> -"Recast.AI is now called SAP Conversational AI, this matcher  will stop "
This line needs to stay the same, that's why the tests are failing. Our localization expects the strings to be literal ones from the code base. 

The previous PR that added the Hindi translation, probably followed the steps for translating opsdroid.

2020-10-02 14:43 UTC, FabioRosado commented
Hello @virejdasani  thank you for Raising this PR and wanting to help the project. 

I've added a comment on the translation strings - they need to be set as they were otherwise the tests will fail - like they are now.

You can check the steps for translating to a language on the [localization documentation](https://docs.opsdroid.dev/en/stable/contributing.html?highlight=translation#localization)

2020-10-04 13:05 UTC, FabioRosado approved these changes
Hello @virejdasani  thank you for updating this PR. I've noticed that you commented out some of the translations that you added previously, is this intentional? could be good to have them in the file.

I'm setting this PR as approved so it counts for your Hacktoberfest, but would be great to hear from you about this 👍

2020-10-04 13:09 UTC, virejdasani commented
Oh, I'm sorry, I did'nt realize I did that. I'll get to that ASAP

2020-10-04 13:25 UTC, FabioRosado commented
Awesome thanks! As soon as CI finishes I will merge this, thank you so much for raising the PR and for spotting and fixing the issue 😄 👍

2020-10-04 13:27 UTC, virejdasani commented
I am extremely sorry, I am not sure why the tests failed. 
This is my first time doing this. Can you help me out?

2020-10-04 13:48 UTC, merged

2020-10-04 13:48 UTC, FabioRosado commented
Again thank you so much for fixing those annoying errors and for the patience this PR is now merged 😄 👍

2020-10-04 13:52 UTC, virejdasani commented
Thanks a lot!
Also, I just wanted to ask, do you know why the PR is still not accepted in my Hacktoberfest?
I assumed it would be accepted as soon as this merge happens...

2020-10-04 13:59 UTC, FabioRosado commented
With the new changes they said that any PR that has been approved, merged or has the hacktoberfest-accepted tag will count so It should be added straight away unless they take a while to process it now?

I'm going to work now, if in two hours it doesn't slow let me know and I'll add the "hacktoberfest-approved" tag.

2020-10-04 15:54 UTC, virejdasani commented
It has been over 2 hours ad the PR is still not accepted.
I'd appreciate it if you could tag it with the hacktoberfest tag.
Thanks in advance!

2020-10-05 03:39 UTC, virejdasani commented
One day later, they have still not accepted it...

2020-10-05 13:06 UTC, FabioRosado commented
I've added the hacktoberfest-accepted label as well. This shouldn't be needed since it was approved and merged but perhaps the label will unlock the PR in your hacktoberfest dashboard

2020-10-05 13:58 UTC, virejdasani commented
I'm not sure why, but for some reason, the PR is still in review.
![hacktober-in-review](https://user-images.githubusercontent.com/67495678/95088685-e4a12700-0740-11eb-8018-715efd687bee.png)
Anyway, thanks for adding the tag

2020-10-05 14:05 UTC, virejdasani commented
Thanks a lot!