Handling encryption with matrix connection in the Dockerfile build
opsdroid/opsdroid pull request #1690
Opened 2020-12-30 02:19 UTC by dud1337

The matrix connection's encryption handling doesn't work with the current dev docker build due to missing dependencies. `nio.crypto.ENCRYPTION_ENABLED` returns `False`

To solve this, 3 dependencies are installed:
* `libffi-dev` via `apk`
* `python-olm` via `pip`
* `matrix-nio[e2e]` via `pip`

I've tested this in an encrypted room.

It should be noted that this by default **doesn't have persistence on the generated device key**. Perhaps a volume should be considered?

Relates to #1676

2021-01-04 12:00 UTC, jacobtomlinson commented
cc @Cadair

2021-01-04 12:03 UTC, Cadair commented on setup.cfg
> +	matrix-nio[e2e]
I don't think we want this here like this.

There are two things, I think `python-olm` should be a dependency of `matrix-nio[e2e]` anyway, also I think that we don't want to require e2e for installing the matrix connector, I think it needs to be opt-in as it's difficult to install on non-linux platforms at the moment.

What I propose is this:
```suggestion
connector_matrix_e2e =
	matrix-nio[e2e]
```

2021-01-04 16:54 UTC, dud1337 commented
>which will add a new extra so you would do pip install opsdroid[connector_matrix, connector_matrix_e2e] to get all the e2e deps.

Sounds good. As long as it's in the docker image for my laziness :]

I'll say that in the long run, from the matrix perspective, having e2e as "optional" feels wrong, but I understand re: installation difficulties on other platforms.

2021-01-04 18:15 UTC, Cadair commented
> I'll say that in the long run, from the matrix perspective, having e2e as "optional" feels wrong

I agree, and the packaging situation is improving for the olm library and bindings, but basically until it's on PyPI it's impractical for us to install it by default.

2021-01-04 18:15 UTC, Cadair approved these changes

2021-01-04 18:16 UTC, Cadair commented
@jacobtomlinson Are the test fails here expected?

2021-01-04 18:17 UTC, Cadair requested changes
Well I am going to assume this test fail isn't expected :stuck_out_tongue: 

https://github.com/opsdroid/opsdroid/pull/1690/checks?check_run_id=1645033142#step:5:463

2021-01-05 09:40 UTC, Cadair commented
It seems that it's not finding olm when installing python-olm?

2021-01-05 10:23 UTC, Cadair commented
I looked into the error and got a little carried away, I hope you don't mind.

I have changed two things:

1. I excluded the new `connector_matrix_e2e` from being included in the `all` extra.
2. I skipped the install step for the docker builds to save a little time.

2021-01-05 10:26 UTC, Cadair approved these changes

2021-01-05 10:28 UTC, merged

2021-01-05 10:39 UTC, dud1337 commented
Thanks; I was dreading fixing the docker builds on windows anyway.