Fix broken contributing links
opsdroid/opsdroid pull request #1819
Opened 2021-08-11 21:43 UTC by arusahni

# Description

This fixes the outdated/broken contribution link on the index pages.

Fixes #1816 

## Status
**READY**

## Type of change

- Documentation (fix or adds documentation)

# How Has This Been Tested?

-  I viewed the rendered Markdown

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-12 15:33 UTC, jacobtomlinson requested changes
Thanks for this. I don't think we need the `index.html` or title anchor in these links.

2021-08-12 15:33 UTC, jacobtomlinson commented on README.md
> +This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/index.html#contributing)].
```suggestion
This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/)].
```

2021-08-12 15:33 UTC, jacobtomlinson commented on docs/index.md
> +This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/index.html#contributing)].
```suggestion
This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/)].
```

2021-08-12 15:34 UTC, jacobtomlinson commented
There is also a conflict because one of these links was updated in #1818. Could you please resolve this.

2021-08-12 22:01 UTC, arusahni commented on README.md
> +This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/index.html#contributing)].
Done.

2021-08-12 22:01 UTC, arusahni commented on docs/index.md
> +This project exists thanks to all the people who contribute. [[Contribute](https://docs.opsdroid.dev/en/stable/contributing/index.html#contributing)].
Done!

2021-08-12 22:03 UTC, arusahni commented
@jacobtomlinson I rebased on master and resolved the conflict. LMK if you'd like to see anything else.

2021-08-13 18:41 UTC, cognifloyd approved these changes

2021-08-16 15:42 UTC, jacobtomlinson approved these changes

2021-08-16 15:42 UTC, merged

2021-08-16 15:43 UTC, jacobtomlinson commented
Thanks @arusahni