Log errors instead of printing them
opsdroid/opsdroid pull request #1834
Opened 2021-09-30 10:02 UTC by jacobtomlinson

Looks like some errors were being printed instead of logged. This is causing them to be truncated.

2021-10-05 09:49 UTC, Cadair requested changes
Wait no.

I made these print on purpose. During the teardown of the interpreter the logger can vanish leading to these lines throwing even more errors.

Let me see if I can dredge up that change.

2021-10-05 09:51 UTC, Cadair commented
https://github.com/opsdroid/opsdroid/pull/1069/files#r327158672

2021-10-05 10:37 UTC, jacobtomlinson commented
Hrm that's a shame. It looks like the print statements here are truncating the errors. Do you have any thoughts on how we can fix that?

2021-10-05 10:51 UTC, Cadair commented
Do you mean that it's not printing the whole traceback?

2021-10-06 15:20 UTC, jacobtomlinson commented
Yeah

2023-02-06 00:05 UTC, xloem commented
I opened #1983 before noticing this.

It looks like it would make sense to wrap logging of the exceptions in `sys.is_finalizing` https://github.com/python/cpython/issues/70976#issuecomment-1093712202 note also python 3.10 is much more stable for this case.

I'd think ideally these exceptions would be passed to user code.

2024-04-25 10:47 UTC, jacobtomlinson commented
Closing as super stale

2024-04-25 10:47 UTC, closed without merging