Search Channel id by name
opsdroid/opsdroid pull request #1908
Opened 2022-05-03 05:38 UTC by chillipeper

# Description

Previously PR #1765  was opened for this, but it was never finished. This is the finished version of it.

Fixes #1699 

## Status
**READY** 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- Added relevant tests 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-14 13:19 UTC, FabioRosado requested changes
Added some comments, let me know if you have bandwidth to address them, if not I'm happy to do a follow up PR 😄

2022-05-15 10:27 UTC, chillipeper commented on docs/connectors/slack.md
> -\* when `socket-mode` is true, you need to set also an `app-token` (more info: [app level tokens](https://api.slack.com/authentication/token-types#app))
this is not deleted, this was moved to line 46 and 47 of the modified version

2022-05-15 10:28 UTC, chillipeper commented on docs/connectors/slack.md
> -** In order for `bot-name` and/or `icon-emoji` to work, the `chat:write.customize` scope will have to be selected
same as above, lines 51-52

2022-05-15 12:21 UTC, FabioRosado commented on docs/connectors/slack.md
> -\* when `socket-mode` is true, you need to set also an `app-token` (more info: [app level tokens](https://api.slack.com/authentication/token-types#app))
Uh sorry! I'm trying the new view and I can't see that which is weird. Thank you for the patience and apologies!

2022-05-15 12:30 UTC, FabioRosado approved these changes
Thank you for working (or reviving this work and finishing it). Providing that I didn't bork the conflict resolution I will merge it once CI passes 😄

2022-05-15 15:25 UTC, FabioRosado commented
Seems like I broke the tests, will fix them and push the changes if you are happy with it 👍

2022-05-15 16:07 UTC, merged

2022-05-15 16:08 UTC, FabioRosado commented
Thank you again for implementing this!